spring.application.name=billing
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
server.port=8080
spring.datasource.url=jdbc:postgresql://postgres-billing:5432/${BILLING_DB_NAME}
spring.datasource.username=${BILLING_DB_USERNAME}
spring.datasource.password=${BILLING_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework=INFO
logging.level.com.example.billing=DEBUG
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.time-zone=UTC
# spring.flyway.enabled=true
# spring.flyway.locations=classpath:db/migration
# spring.flyway.baseline-on-migrate=true
# spring.flyway.baseline-version-migration=true

